config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'articles#index'

  get 'articles/my'
  devise_for :users
 

  resources :articles

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image
    has_many :comments, dependent: :destroy
    validates :title,:description, presence: true,length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

 before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:fullname, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:fullname, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:fullname,:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: %i[ show edit update]

    def index 
        @articles = Article.order("created_at DESC").all
    end

    def my 
        @articles = Article.order("created_at DESC").all
    end

    def new 
        @article = Article.new 
    end

    def create
        @article = Article.new(article_params)
        
        respond_to do |format|
            if @article.save
              format.html { redirect_to '/', notice: "Article was successfully created." }
              format.json { render :show, status: :created, location: @article }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @article.errors, status: :unprocessable_entity }
            end
          end
    end

    def show
    end

    def edit
    end

    def update
        respond_to do |format|
          if @article.update(article_params)
            format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
            format.json { render :show, status: :ok, location: @article }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @article.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        respond_to do |format|
          format.html { redirect_to '/', notice: "Article was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :image, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end

      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
     
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control form-input" %>
  </div>
 
   <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description , class:"form-control form-input" %>
  </div>

    <div class="form-group">
    <%= form.label :image %><br>
    <%= form.file_field :image, class:"form-control form-input"  %>
   </div>
   <%= form.hidden_field :user_id, value: current_user.id  %>
 
  <p>
    <%= form.submit class:"btn btn-primary form-button" %>
  </p>
 
<% end %>
 

app/views/articles/edit.html.erb
<h1 style="text-align:center;">Edit Article</h1>
 <div class="container">
<div class="card">
<div class="container">
<%= render 'form', article: @article %>
 
 </div>

 </div>
<%= link_to 'Back', articles_path, class:"btn btn-dark back-button" %>
</div>

app/views/articles/index.html.erb
 <div class="container my-5">
          <div class="row d-flex justify-content-center">
              <div class="col-12">
               
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <div class="row">
                        <% if @articles %>
                        <% @articles.each do |article| %>
                            <div class="col-12 col-md-6 col-xl-3 ">
                                <div  class="card mr-3">
                                <% if article.image.attached? %>
                                	<%= image_tag(article.image, :alt => "article", class:"card-img-top") %>
                                    <%end%>
                                    <div class="card-body">
                                      <h5 class="card-title"><%= article.title %></h5>
                                      <p class="card-text"><%= article.description[0..100] %>...</p>
                                    
                                    <%= link_to 'Read more', article_path(article),class:"btn btn-primary" %>
                                    <% if article.user_id == current_user.id%>
                                    <%= link_to 'Edit', edit_article_path(article),class:"btn btn-success btn-small" %>
                                    <%= link_to 'Delete', article_path(article),method: :delete,data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-small" %>
                                    <%end%>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                        <%end%>
                            
     
                        </div>
                      </div>

                       
                  </div>
            
          </div>
          </div>

            
      </div>

      

app/views/articles/my.html.erb
 <div class="container my-5">
          <div class="row d-flex justify-content-center">
              <div class="col-12">
               
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <div class="row">
                        <% if @articles %>
                        <% @articles.each do |article| %>
                        <% if article.user_id == current_user.id%>
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                <% if article.image.attached? %>
                                	<%= image_tag(article.image, :alt => "article", class:"card-img-top") %>
                                    <%end%>
                                    <div class="card-body">
                                      <h5 class="card-title"><%= article.title %></h5>
                                      <p class="card-text"><%= article.description[0..100] %>...</p>
                                    
                                    <%= link_to 'Read more', article_path(article),class:"btn btn-primary" %>
                                    <% if article.user_id == current_user.id%>
                                    <%= link_to 'Edit', edit_article_path(article),class:"btn btn-success btn-small" %>
                                    <%= link_to 'Delete', article_path(article),method: :delete,data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-small" %>
                                    <%end%>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                        <%end%>
                        <%end%>
                            
     
                        </div>
                      </div>

                       
                  </div>
            
          </div>
          </div>

            
      </div>

      

app/views/articles/new.html.erb
<h1 style="text-align:center;">New Article</h1>
 <div class="container">
<div class="card">
<div class="container">
<%= render 'form', article: @article %>
 

</div>

 </div>
 <%= link_to 'Back', articles_path, class:"btn btn-dark back-button" %>
 </div>

app/views/articles/show.html.erb
<div style="margin:40px;" class="conatiner">
<div class="row">

    <div class="col-md-6 show-image">
      <% if @article.image.attached? %>
        <%= image_tag(@article.image, :alt => "article", class:"article-image") %>
        <%end%>
    </div>
    <div class="col-md-4">
        <h4><%= @article.title%></h4>
        <p class="text-muted"><%= @article.description%></p>
        <% if @article.user_id == current_user.id%>
        <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-success" %>
    <%= link_to 'Delete', article_path(@article),method: :delete,data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
        <%end%>
    </div>
</div>

</div>



<div class="container">
<div class="card">
<h2 style="margin:20px;">Comments</h2>
<div class="conatiner">
<%= render @article.comments %>
</div>
 
<div class="container"> 
<%= render 'comments/form' %>
</div>
</div>
</div>

app/views/comments/_comment.html.erb
<div class="container">

  <p>&nbsp;<b><%= comment.commenter %>:</b><%= comment.body %></p> 

</div>
 

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
 <p>
    
    <%= form.hidden_field :commenter, value: current_user.username %>
  </p>
  
  <div class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control form-input" %>
  </div>
  <p>
    <%= form.submit class:"btn btn-primary form-button" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogspot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  </head>

  <body>
  <%= render "welcome/header" %>
  
   <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>


            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcome/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Blogspot</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/articles/new">Create Blog</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="/articles/my">My Blogs</a>
              </li>
            </ul>
            <div class="d-flex">
             
             <% if user_signed_in? %>
 <p style="color:white;margin:10px;">Welcome <b><%= current_user.username%></b></p>
  
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-outline-success'  %>
<% else %>
     <a href="/users/sign_up" class="btn btn-outline-success" type="submit">Sign up</a>
              &nbsp;
      <a href="/users/sign_in" class="btn btn-outline-success" type="submit">Log in</a>
           <% end %>
          </div>
          </div>
        </div>
      </nav>

app/views/welcome/index.html.erb
 <div class="container my-5">
          <div class="row d-flex justify-content-center">
              <div class="col-12">
               
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <div class="row">
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                    <img src="https://themesberg.s3.us-east-2.amazonaws.com/public/posts/bootstrap-themes-summer-sale.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">35% discount for premium Bootstrap Themes, Templates, UI Kits</h5>
                                      <p class="card-text">We’re getting nearer to the end of summer and because we know that this period can make a serious dent in your pocket..</p>
                                      <a href="#" class="btn btn-primary">Read more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                    <img src="https://themesberg.s3.us-east-2.amazonaws.com/public/posts/gpt-3-tailwind-css-code-generator.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">We built an OpenAI powered Tailwind CSS code generator using GPT-3</h5>
                                      <p class="card-text">A couple of days ago we got access to the OpenAI’s Beta API platform and I had the occasion to play around with it...</p>
                                      <a href="#" class="btn btn-primary">Read more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                    <img src="https://themesberg.s3.us-east-2.amazonaws.com/public/posts/bootstrap-5-tutorial/bootstrap-5-tutorial.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">Bootstrap 5 tutorial: learn how to get started without jQuery</h5>
                                      <p class="card-text">We’re getting nearer to the end of summer and because we know that this period can make a serious dent in your pocket..</p>
                                      <a href="#" class="btn btn-primary">Read more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                    <img src="https://themesberg.s3.us-east-2.amazonaws.com/public/posts/angular-10/angular-10-officially-released-dropping-ie-9-10.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">Angular 10 officially released deprecating support for IE 9 and 10</h5>
                                      <p class="card-text">If you’ve been using Angular for your web projects I’m glad to let you know that following this major update to version...</p>
                                      <a href="#" class="btn btn-primary">Read more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-xl-3 mb-4">
                                <div class="card mr-3">
                                    <img src="https://themesberg.s3.us-east-2.amazonaws.com/public/posts/angular-10/angular-10-officially-released-dropping-ie-9-10.jpg" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">Angular 10 officially released deprecating support for IE 9 and 10</h5>
                                      <p class="card-text">If you’ve been using Angular for your web projects I’m glad to let you know that following this major update to version...</p>
                                      <a href="#" class="btn btn-primary">Read more</a>
                                    </div>
                                </div>
                            </div>

                                
                        </div>
                      </div>

                       
                  </div>
            
          </div>
          </div>

            
      </div>